# Generated by Django 5.2.1 on 2025-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carts_id_alter_carts_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='qty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
